services:
  database:
    image: 'postgres:18-alpine'
    networks:
      - db-network
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
  backend:
    build: backend/
    env_file: "backend/.env"
    volumes:
      - ./scraping:/app/scraping
    ports:
      - 8888:5000
    depends_on:
      - database
    networks:
      - default
      - db-network
    restart: unless-stopped
  frontend:
    build: frontend/app
    ports:
      - 8887:80
    restart: unless-stopped
  

networks: 
  default:
  db-network:
    internal: true
volumes:
  db-data:
