services:
  database:
    image: 'postgres:18-alpine'
    networks:
      - db-network
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
  backend:
    build: backend/
    env_file: "backend/.env"
    environment:
      FRONTEND_URL=http://localhost:7887
    volumes:
      - ./scraping:/app/scraping
    ports:
      - 7888:5000
    depends_on:
      - database
    networks:
      - default
      - db-network
    restart: unless-stopped
  frontend:
    build: 
      context: ./frontend/app
      args:
        REACT_APP_BACKEND_URL: http://localhost:7888
    ports:
      - 7887:80
    restart: unless-stopped
  

networks: 
  default:
  db-network:
    internal: true
volumes:
  db-data:
